name = "SimpleDataStructures"
uuid = "f5799a6c-8df6-11ea-0edd-2d709082b0c5"
authors = ["harryscholes <harryscholes@gmail.com>"]
version = "0.1.0"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
